### PR TITLE
add instructions for debian

### PR DESCRIPTION
**Pull request by eiro**

### CODE REVIEW

**Comment by fzwoch** [comment]
Hi, Thanks. The first part is definitely helpful for people. I'm unsure about the second part as it is very dependent on how you have installed OBS. E.g. for Debian's own package this is correct - if you have it compiled yourself it will most likely install itself in the `/usr/local` prefix. Also I think there is also a per-user directory for plugins - however I never git a full picture about the paths and their search order.

Perhaps this needs another sentence. And also - maybe it makes sense to use meson's prefix system so you can configure it to `/usr` or `/usr/local` and simply use `ninja install` to have the plugin copied to the right location.

**Comment by eiro** [comment]
hello,

On Wed, Sep 04, 2019 at 02:49:29AM -0700, Florian Zwoch wrote:
> I'm unsure about the second part as it is very dependent on how you
> have installed OBS. E.g. for Debian's own package this is correct

i wrote those lines for a complete beginner and hopping that if you were
able to install the obs using another way, you'll be able to adapt the
command.

>  if you have it compiled yourself it will most likely install itself
>  in the `/usr/local` prefix. Also I think there is also a per-user
>  directory for plugins - however I never git a full picture about the
>  paths and their search order.

a per-user directory would definitely be helful. i was unhappy
about copying in another place than /usrlocal but i had no time to
experiment. i guess this help is better than nothing :)

> Perhaps this needs another sentence. And also - maybe it makes sense to use meson's prefix system so you can configure it to `/usr` or `/usr/local` and simply use `ninja install` to have the plugin copied to the right location.

i have very few time i can dedicate helping to improve the doc and
meson/ninja is something i'm really not interested in but i'll do some
very basic tests.

off topic: the video capture has quality is very jerky so i can't
publish the real capture i made. is there a place to talk about this? a
mailing list or something?

regards
marc

**Comment by fzwoch** [comment]
I guess you can find me on the OBS Discord server as "Tuna". The avatar is the same as it is here.

**Comment by eiro** [comment]
hello,

On Wed, Sep 04, 2019 at 08:52:42AM -0700, Florian Zwoch wrote:
> I guess you can find me on the OBS Discord server as "Tuna". The avatar is the same as it is here.

no offense but no, thank you: those kind of tools are really anyoing to
me. but thanks to your invite, i found the irc channel :)

regards.
marc

**Comment by fzwoch** [comment]
A lot has changed since. There is now a `Dockerfile` which should create a build enironment when in need.

**Pull request closed without merging**
