### PR TITLE
Use XDG_RUNTIME_DIR for default socket path

### PR DESCRIPTION
**Pull request by TingPing**
This works better in Flatpak and is just the better dir

### CODE REVIEW

**Comment by fzwoch** [comment]
Thanks, I assumed there was a better way but I didn't know about these. Also `g_autofree()` seems to be worth reading about..

**Comment by TingPing** [comment]
> Also g_autofree() seems to be worth reading about..

It is the best thing to ever happen to C :P

**Comment by TingPing** [comment]
BTW this plugin is being shipped in the OBS package on Flathub.

**Comment by fzwoch** [comment]
That sounds awesome! Is that being found on the OBS page? I always wanted to try how these flatpaks are being used but never got around to do it yet..

**Comment by TingPing** [comment]
No, I haven't approached upstream about promoting it: https://beta.flathub.org/apps/details/com.obsproject.Studio

**Comment by TingPing** [comment]
BTW have you looked into making a Pipewire plugin for OBS? That seems like the best way to expose this in the future rather than the dbus interface.

**Comment by fzwoch** [comment]
No I haven't. I could not grasp what it exactly it is and how it works yet. Also it isn't part of Debian Sid yet, so I figured it is not ready. And I'm not sure how another client server model helps here. Ultimately for this purpose we need to get the data from the composer or GNOME anyway.. but I'll keep my eyes all around to find other and better solutions.

**Comment by TingPing** [comment]
There are a few main upsides from my perspective though I agree it is a young project:

- It is potentially a cross DE abstraction
- It is a complete solution that can cover audio, webcams, etc
- It is designed to be sandboxing friendly and Flatpak already has an explicit permission to allow it

**Pull request merged**
